### ISSUE TITLE
A greet from Indonesia

### ISSUE THREAD

**Issue by thebluetropics** [katahiromz/ImeStudy#4]
@katahiromz

Hi, Katayama Hirofumi!

I am very happy to found out this study.

Can we discuss this furthermore? I have zero experience on IME handling in Win32 applications...

**Comment by katahiromz** [comment]
What's up?

**Comment by katahiromz** [comment]
The current implementation is not stable and limited in functionality. Do you have any present for me?

**Comment by thebluetropics** [comment]
Nope, I just want to know how can I work with IME in Win32 API. Looks like we are here on the same road, using IMM rather than using TSF (Text Services Framework).

**Comment by thebluetropics** [comment]
Have you written a code that capable of showing/hiding, triggering an IME candidate window?

**Comment by katahiromz** [comment]
The candidate list not working yet.
The status window display is unstable.
The IME hotkeys not working correctly.

Here is Japanese free IME :
https://github.com/katahiromz/mzimeja

**Comment by katahiromz** [comment]
I am still unable to manage the internal status of IMM/IME.

**Comment by thebluetropics** [comment]
Why is IME handling in Win32 application is this hard?

**Comment by katahiromz** [comment]
I am writing the code of the system beyond one application.

**Comment by katahiromz** [comment]
Win32 GWES has complicated structure. Processes, Threads, Modules, Control path, Windows, Messaging etc.

**Comment by katahiromz** [comment]
To get the system info, we have to use kernel debugger (such as WinDbg).
Kernel debugging needs a special skill and howto knowledge.
There's difficulty in fulfilling the mission.

**Comment by katahiromz** [comment]
In addition, the final implementation should be the same or similar to Windows. But we can't use Ctrl+C and Ctrl+V for that.

**Comment by katahiromz** [comment]
```c
#include <imm.h>
...
HIMC hImc = ImmGetContext(hWnd);
...(Use hImc here)...
ImmReleaseContext(hWnd, hImc);
```
This is a basic form to control the ime.

**Comment by katahiromz** [comment]
https://katahiromz.web.fc2.com/colony3rd/imehackerz/en/ImmNotifyIME.html
https://katahiromz.web.fc2.com/colony3rd/imehackerz/en/NI_OPENCANDIDATE.html
https://katahiromz.web.fc2.com/colony3rd/imehackerz/en/NI_CLOSECANDIDATE.html
